//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Account_Download
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARAccount
    {
        public string Id { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Name { get; set; }
        public string BillingStreet { get; set; }
        public string BillingCity { get; set; }
        public string BillingState { get; set; }
        public string BillingPostalCode { get; set; }
        public string Phone { get; set; }
        public string Website { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
        public Nullable<double> Parts__c { get; set; }
        public Nullable<double> Total_assets__c { get; set; }
        public string Industry_Description__c { get; set; }
        public string Asset_Range_Lower__c { get; set; }
        public string Asset_Range_Upper__c { get; set; }
        public string Advisor__c { get; set; }
        public Nullable<System.DateTime> Last_Lead_RFI__c { get; set; }
        public string Provider_1__c { get; set; }
        public string Heads_Up__c { get; set; }
        public string YearEstablished__c { get; set; }
        public string Primary_Contact__c { get; set; }
        public string Client_Territories__c { get; set; }
        public Nullable<double> NumDCPlans__c { get; set; }
        public string Status__c { get; set; }
        public string Federal_ID__c { get; set; }
        public string Account_Status__c { get; set; }
        public string Account_Type__c { get; set; }
        public string Advisor_City__c { get; set; }
        public string Tier__c { get; set; }
        public string Advisor_State__c { get; set; }
        public string Client_Type__c { get; set; }
        public string Advisor_Zip__c { get; set; }
        public string Advisor_Email__c { get; set; }
        public string AdvisorAddress__c { get; set; }
        public string CRD__c { get; set; }
        public Nullable<double> X1M_5M__c { get; set; }
        public Nullable<double> X5M_25M__c { get; set; }
        public Nullable<double> X25M_and_Up__c { get; set; }
        public string Industry_Code__c { get; set; }
        public string Industry_Subsector__c { get; set; }
        public string PGID__c { get; set; }
        public string FFID__c { get; set; }
        public Nullable<bool> Monthly_Activity_Reporting__c { get; set; }
        public string Lead_Distribution_Email_Addresses__c { get; set; }
        public string Client_Territories_DB__c { get; set; }
        public string CallListID__c { get; set; }
        public string Do_Not_Call__c { get; set; }
        public string Industry_and_Plan_Type__c { get; set; }
        public string Advisor_Firm_Name__c { get; set; }
        public string Length_Advisor__c { get; set; }
        public string Length_Provider__c { get; set; }
        public Nullable<System.DateTime> Last_Review_Date__c { get; set; }
        public Nullable<System.DateTime> Date_of_Last_Provider_Change__c { get; set; }
        public Nullable<bool> DecisionMaker_Identified__c { get; set; }
        public Nullable<System.DateTime> Next_RFP_Timing__c { get; set; }
        public string Satisfiers_Noted__c { get; set; }
        public string Painpoints_Noted__c { get; set; }
        public Nullable<System.DateTime> Date_of_Last_Advisor_Change__c { get; set; }
        public string Last_Filing_Year__c { get; set; }
    }
}
