//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Account_Download
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARContact
    {
        public string Id { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string AccountId { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Salutation { get; set; }
        public string Name { get; set; }
        public string MailingStreet { get; set; }
        public string MailingCity { get; set; }
        public string MailingState { get; set; }
        public string MailingPostalCode { get; set; }
        public string MailingCountry { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string MobilePhone { get; set; }
        public string Email { get; set; }
        public string LeadSource { get; set; }
        public string OwnerId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedById { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string LastModifiedById { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
        public string LastCURequestDate { get; set; }
        public string LastCUUpdateDate { get; set; }
        public string EmailBouncedReason { get; set; }
        public Nullable<System.DateTime> EmailBouncedDate { get; set; }
        public string ConnectionReceivedId { get; set; }
        public string ConnectionSentId { get; set; }
        public Nullable<bool> Contact_No_Longer_There__c { get; set; }
        public string Best_Way_to_ReachL__c { get; set; }
        public Nullable<bool> Email_Confirmed__c { get; set; }
        public string Admin_Phone__c { get; set; }
        public string Admin_Name__c { get; set; }
        public string Title__c { get; set; }
        public Nullable<bool> Duplicate_Contact_REMOVE__c { get; set; }
        public string Contact_Source__c { get; set; }
        public Nullable<bool> Contact_Confirmed__c { get; set; }
        public Nullable<System.DateTime> Last_Marketing_Response__c { get; set; }
        public string Direct_Mkt_Client_Contact__c { get; set; }
        public Nullable<bool> Click_Thru__c { get; set; }
        public Nullable<bool> Freq_Response__c { get; set; }
        public Nullable<bool> Duplicate__c { get; set; }
        public string Note_Heads_up__c { get; set; }
        public string RepRegulatoryID { get; set; }
        public string MAILINGLATITUDE { get; set; }
        public string MAILINGLONGITUDE { get; set; }
        public Nullable<bool> MAIN_DECISION_MAKER__C { get; set; }
        public string PRIORITY__C { get; set; }
        public string REPREGULATORYID__C { get; set; }
        public string INSURANCE_LICENSED__C { get; set; }
        public Nullable<double> AUM__C { get; set; }
        public Nullable<double> PRODUCTION__C { get; set; }
        public Nullable<double> LPL_AGE__C { get; set; }
        public string LPL_NON_PRODUCER__C { get; set; }
        public string LICENSES__C { get; set; }
        public string LICENSED_SINCE__C { get; set; }
        public Nullable<bool> RETIREMENT_PLAN_ADVISOR__C { get; set; }
        public Nullable<double> NUMBER_OF_RETIREMENT_PLAN__C { get; set; }
        public string Date_Email_Verified__c { get; set; }
        public string Email_Verification_Rating__c { get; set; }
        public string BOUNCED_EMAIL__c { get; set; }
    }
}
