//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Account_Download
{
    using System;
    using System.Collections.Generic;
    
    public partial class AROpportunity
    {
        public string Id { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string AccountId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string StageName { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string LeadSource { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public Nullable<bool> HasOpportunityLineItem { get; set; }
        public string OwnerId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedById { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string LastModifiedById { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
        public Nullable<int> FiscalQuarter { get; set; }
        public Nullable<int> FiscalYear { get; set; }
        public string Fiscal { get; set; }
        public Nullable<bool> Follow_Up_on_Marketing_Campaign__c { get; set; }
        public string Reason_for_NIGO__c { get; set; }
        public Nullable<double> Assets__c { get; set; }
        public Nullable<double> Participants__c { get; set; }
        public Nullable<bool> Request_for_Information__c { get; set; }
        public string Invoice_Status__c { get; set; }
        public string Commission_Status__c { get; set; }
        public string Reason_for_Decline_if_applicable__c { get; set; }
        public string Client_Oppty_Type__c { get; set; }
        public string Plan_Type__c { get; set; }
        public string Current_Platform_Services__c { get; set; }
        public string Platform_Relationship_Length__c { get; set; }
        public string Current_Consultant_Advisor__c { get; set; }
        public string Advisor_Relationship_Length__c { get; set; }
        public string Plan_Strength_Weakness__c { get; set; }
        public string Decision_Making_Process__c { get; set; }
        public string Next_Steps__c { get; set; }
        public string Opportunity_Type__c { get; set; }
        public Nullable<double> Leads_per_month__c { get; set; }
        public string Opportunity_stage__c { get; set; }
        public string Acccount_Type__c { get; set; }
        public string Current_Auditor_Relationship_Length__c { get; set; }
        public string Payroll__c { get; set; }
        public string Client_Manager__c { get; set; }
        public string Client_Manager_Phone__c { get; set; }
        public string Client_Manager_Email__c { get; set; }
        public string Parent_Account__c { get; set; }
        public Nullable<System.DateTime> Appointment_Date__c { get; set; }
        public string PrimaryContact__c { get; set; }
        public string Primary_Contact_Phone__c { get; set; }
        public string Primary_Contact_Email__c { get; set; }
        public string Primary_Contact_Best_Way_to_Reach__c { get; set; }
        public string Primary_Contact_Title__c { get; set; }
        public Nullable<double> DB_Plan_Assets__c { get; set; }
        public string Current_Auditor_Siff_only__c { get; set; }
        public string Number_of_Personnel_File_Locations__c { get; set; }
        public string Referred_By__c { get; set; }
        public Nullable<double> Total_Leads__c { get; set; }
        public string Notes_on_Lead_Outcome__c { get; set; }
        public Nullable<bool> Decision_Maker__c { get; set; }
        public string Timeframe_of_Meeting__c { get; set; }
        public string Meeting_Format__c { get; set; }
        public string Pain_Point_Identification__c { get; set; }
        public string Lead_Completeness__c { get; set; }
        public Nullable<bool> Meeting_Invitation__c { get; set; }
        public string RFI_Request_Type__c { get; set; }
        public string Account_ID { get; set; }
        public Nullable<double> Probability__c { get; set; }
        public Nullable<System.DateTime> AR_Sales_1st_Meeting__c { get; set; }
        public Nullable<System.DateTime> AR_Sales_Proposal_Sent__c { get; set; }
        public Nullable<System.DateTime> AR_Sales_Service_Agreement_Sent__c { get; set; }
        public Nullable<System.DateTime> AR_Sales_Verbal_Commitment__c { get; set; }
        public Nullable<System.DateTime> AR_Sales_Contract_Received__c { get; set; }
        public string APPOINTMENT_TIME__C { get; set; }
        public string Lead_sharing__c { get; set; }
        public string Satisfiers_Noted__c { get; set; }
        public string Painpoints_Noted__c { get; set; }
    }
}
