//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Account_Download
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTask
    {
        public string Id { get; set; }
        public string WhoId { get; set; }
        public string WhatId { get; set; }
        public string Subject { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public string Status { get; set; }
        public string Priority { get; set; }
        public string OwnerId { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string AccountId { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedById { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string LastModifiedById { get; set; }
        public Nullable<System.DateTime> ReminderDateTime { get; set; }
        public Nullable<bool> IsReminderSet { get; set; }
        public Nullable<bool> IsRecurrence { get; set; }
        public string Short_Call_Notes__c { get; set; }
        public string CallType__c { get; set; }
        public string Contact_Type__c { get; set; }
        public string Conversation__c { get; set; }
        public string TimeFrame__c { get; set; }
        public string Client_Territories__c { get; set; }
    }
}
